//
// Created by paulo on 14/06/19.
//

#ifndef TRABALHO_1_CLION_COMANDOGETAPRESENTACOESFROMEVENTO_H
#define TRABALHO_1_CLION_COMANDOGETAPRESENTACOESFROMEVENTO_H


class ComandoGetApresentacoesFromEvento {

};


#endif //TRABALHO_1_CLION_COMANDOGETAPRESENTACOESFROMEVENTO_H
